name: deploy book
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo snap install mdbook
      - run: mdbook build ./book
      - run: >
          git worktree add --orphan -B gh_pages ../gh_pages 
          && cp -r ./book/book/* ../gh_pages 
          && cd ../gh_pages 
          && git config user.name "Deploy from CI" 
          && git config user.email "" 
          && git add . 
          && git commit -a -m 'deploy new book' 
          && git push origin --force gh_pages
